default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: ''
  password: ''

development:
  <<: *default
  database: trade_assistant_bd

test:
  <<: *default
  database: trade_assistant_bd_test

staging:
  <<: *default
  database: trade_assistant_bd_staging

production:
  <<: *default
  database: trade_assistant_bd_production